import fs from 'node:fs/promises';
import path from 'node:path';
const root=process.cwd(), out=path.join(root,'.pages-src');
await fs.rm(out,{recursive:true,force:true}); await fs.mkdir(path.join(out,'_layouts'),{recursive:true});
await fs.writeFile(path.join(out,'_config.yml'),'title: Repo Constellation\nmarkdown: kramdown\ntheme: null\nbaseurl: /repo-constellation\n');
await fs.writeFile(path.join(out,'_layouts/default.html'),`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ page.title }} · Repo Constellation</title><link rel="stylesheet" href="{{ '/assets/site.css' | relative_url }}"></head><body><header><a href="{{ '/' | relative_url }}">Repo Constellation</a><nav><a href="{{ '/' | relative_url }}">首页</a><a href="{{ '/docs/engineering-series-06.html' | relative_url }}">故事连载</a></nav></header><main>{{ content }}</main><footer>Repo Constellation · agent-compose 示例工程</footer></body></html>`);
await fs.mkdir(path.join(out,'assets'),{recursive:true}); await fs.writeFile(path.join(out,'assets/site.css'),`:root{font-family:system-ui,sans-serif;color:#17233b;background:#fafbfd;line-height:1.75}body{max-width:980px;margin:auto;padding:0 22px}header{height:68px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #dce3ec}header a{color:#17233b;text-decoration:none;font-weight:650}nav{display:flex;gap:20px;font-size:.92rem}main{padding:38px 0}h1,h2,h3{line-height:1.25;margin-top:1.8em}h1{font-size:2.25rem}h2{border-left:3px solid #4776a8;padding-left:12px}a{color:#2769a6}img{max-width:100%;display:block;margin:24px auto;border:1px solid #e1e7ef;border-radius:10px}pre{overflow:auto;background:#f0f3f7;padding:16px;border-radius:8px}blockquote{border-left:3px solid #e6a24b;padding-left:16px;color:#536174}table{border-collapse:collapse;width:100%}th,td{border:1px solid #dce3ec;padding:8px;text-align:left}footer{border-top:1px solid #dce3ec;color:#718096;font-size:.85rem;padding:24px 0}`);
const files=['README.md','README.en.md','CONTRIBUTING.md','SECURITY.md',...(await walk(path.join(root,'docs'))).filter(f=>f.endsWith('.md')).map(f=>path.relative(root,f))];
for(const rel of files){const source=await fs.readFile(path.join(root,rel),'utf8');const title=source.match(/^#\s+(.+)$/m)?.[1]??rel;const body=source.replace(/\]\(([^)#]+)\.md(#[^)]+)?\)/g,']($1.html$2)');const target=rel==='README.md'?'index.md':rel;const dest=path.join(out,target);await fs.mkdir(path.dirname(dest),{recursive:true});await fs.writeFile(dest,`---\nlayout: default\ntitle: ${title.replace(/:/g,'-')}\n---\n\n${body}`)}
await copy(path.join(root,'docs/assets'),path.join(out,'docs/assets')); await copy(path.join(root,'docs/assets'),path.join(out,'assets'));
async function walk(dir){const a=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);e.isDirectory()?a.push(...await walk(p)):a.push(p)}return a} async function copy(s,d){await fs.mkdir(d,{recursive:true});for(const e of await fs.readdir(s,{withFileTypes:true})){const a=path.join(s,e.name),b=path.join(d,e.name);e.isDirectory()?await copy(a,b):await fs.copyFile(a,b)}}
